### PR TITLE
added "colour selector"  replacing slider for "hue" parameter

### PR DESCRIPTION
**Pull request by manmohan777**
I think selecting hue using a color selector is easier than a slider so I created a custom color selector and replaced the slider with the "hue" parameter.

### CODE REVIEW

**Comment by manmohan777** [comment]
WhatsApp Image 2020-10-30 at 10 40 59 AM
WhatsApp Image 2020-10-30 at 10 38 19 AM
PaletteBar View
enabled and disabled state

**Comment by shahpiyushv** [comment]
@manmohan777 , thanks for the contribution. Something like this would definitely be useful as people can relate to visual colour more than the arcdegree value. However, this is not matching with rest of the theme of the app. Would it be possible to use something like [this slider](https://github.com/divyanshub024/ColorSeekBar)?

Moreover, the same UI element also needs to show up in the Schedule actions' screen. Internally, we are checking how we can better support this, so that contributors will need to add the UI element at only once place and not two.

**Comment by manmohan777** [comment]
hi Piyush, 
I can change its UI and make it look like a slider as you have demonstrated and create a new UI element then it will be available in the Schedule actions.

**Comment by manmohan777** [comment]
Screenshot_1604991929
this is the changed ui

**Comment by manmohan777** [comment]
Screenshot_1605093630
and in schedule section color selector looks like this

**Comment by shahpiyushv** [comment]
@manmohan777 this looks good now. I will have someone review this. Meanwhile, can you please squash your 11 commits into 1?

**Comment by shahpiyushv** [comment]
@manmohan777 , thanks for the contribution. This has now been merged.

**Pull request merged**
