### PR TITLE
Improve app design and implement dark mode

### PR DESCRIPTION
**Pull request by CodorStelian**
I have made some modifications (mostly in design changes), if you want you can use it and improve Rainmaker app. Of course, it is not necessary to approve this request.
Test it from here  https://github.com/CodorStelian/esp-rainmaker-android/releases/tag/v2.2.1.dark.27be45c-debug
Note: I have tested only on Android 10 and 6.

You're doing a great job!

preview

### CODE REVIEW

**Comment by shahpiyushv** [comment]
@CodorStelian , thanks for the contribution. This dark mode and other changes look interesting. A few changes I spotted are

- Changes to the Profile, Home and Schedules icon.
- Some changes to the "Email cannot be empty" error message.
- Color changes in the title bar

Can you add to this list?

**Comment by CodorStelian** [comment]
1. Do you want to replace home, profile and schedule icons with original icons?

2.There are 10 "cannot" expresions from original strings.xml file, very easy to fix.

3.Do you want only status bar to be colored or both status bar and action bar like original app?

**Comment by shahpiyushv** [comment]
@CodorStelian , I think there is some miscommunication. I was just listing down some of the changes/improvements I spotted and wanted you to provide a list of all other such changes so that we can have a look.

**Comment by CodorStelian** [comment]
@shahpiyushv 
What do you think about this?
new_preview

**Comment by CodorStelian** [comment]
@shahpiyushv 
I'm sorry I didn't read carefully :)) 
I will make a list with changes

**Comment by CodorStelian** [comment]
@shahpiyushv 
My english is not so good so there may be some mistakes. 


- Some changes to the edittext error message and space between fields.
- Changes to some android dependencies and implementations like Google material design.
- Some changes to the launcher app icon.
- Implement dark mode which is supported by Android 9 and up.
- Add icons instead of text actions in action bar.
- Changes to color structure and color pallette.
- Add title for device name dialog.
- Add buttons pressed state color.
- Changes to the device status and power icons.
- Delete all unnecessary drawable resources.
- Add logout icon in user profile page.
- Add device icons for dark theme.
- New checkmark and checkbox icons
- Some changes to dividers and texts in schedules page.

**Comment by CodorStelian** [comment]
New design changes @shahpiyushv 
-Add option to choose default app theme, compatible with older versions of Android.
-Remove Splash Screen time handler.
-Use bitmap Splash Screen instead of layout.
-Use material toolbar and collapsible toolbar with menu icons.
-Use material dialogs instead of the androidx dialogs.
-Use material buttons instead of material card buttons (Progress bar is not supported by default).
-Use material cards instead of the androidx cards.
-Use material switches instead of the androidx switches.
-Some padding and margins changes of the cards layout.
-Other minor changes.

preview2

**Comment by shahpiyushv** [comment]
Hi @CodorStelian , thanks again for all these efforts. We haven't yet got time to review this, but will update you when we are ready for this.

**Comment by CodorStelian** [comment]
No problem, take your time. In meantime I will try to keep it updated (especially for my own use).

**Pull request closed without merging**
